env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends: 'eslint:recommended'
globals:
    currentItem: readonly
    data: readonly
    GmailApp: readonly
    item: readonly
    jQuery: readonly
    logger: readonly
    user: readonly
    xml: readonly
parserOptions:
  ecmaVersion: 12
  sourceType: "module"
rules:
    indent:
        - warn
        - 4
    linebreak-style:
        - error
        - unix
    no-unused-vars: 0
