env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
rules:
    indent:
        - warn
        - 4
    linebreak-style:
        - error
        - unix
